// Generated by scripts/mw19/generate_schema.py from Replay native image tables.
#pragma once
#include <array>
#include <cstdint>

namespace tool::mw19::schema::image_layout {
    inline constexpr std::array<uint32_t, 47> Dxgi{ { 0,  61, 65, 61, 49, 49, 28, 29, 63, 51, 56, 35, 11, 58, 54, 34,
                                                      10, 41, 16, 2,  55, 40, 20, 62, 57, 42, 17, 3,  25, 85, 24, 67,
                                                      26, 71, 72, 74, 75, 77, 78, 80, 83, 84, 95, 96, 98, 99, 31 } };
    inline constexpr std::array<uint32_t, 47> PixelBytes{ { 0, 1, 1, 1,  2, 2, 4, 4, 1, 2, 2, 4,  8, 2, 2, 4,
                                                            8, 4, 8, 16, 2, 4, 8, 1, 2, 4, 8, 16, 4, 2, 4, 4,
                                                            4, 0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0,  0, 0, 4 } };
} // namespace tool::mw19::schema::image_layout
