"""Replay PC image layout, recovered from native tables and upload helpers."""

# Entries 0..46. Source-only formats beyond this range must not be assumed to
# exist in Replay. Format 47 has no usable native DXGI conversion.
DXGI = [0, 61, 65, 61, 49, 49, 28, 29, 63, 51, 56, 35, 11, 58, 54, 34, 10,
        41, 16, 2, 55, 40, 20, 62, 57, 42, 17, 3, 25, 85, 24, 67, 26,
        71, 72, 74, 75, 77, 78, 80, 83, 84, 95, 96, 98, 99, 31]
PIXEL_BYTES = [0, 1, 1, 1, 2, 2, 4, 4, 1, 2, 2, 4, 8, 2, 2, 4, 8,
               4, 8, 16, 2, 4, 8, 1, 2, 4, 8, 16, 4, 2, 4, 4, 4,
               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4]


def metadata():
    return dict(dxgi_table_rva=0x23e25f0, pixel_bytes_table_rva=0x23e4140,
                dxgi_formats=DXGI, pixel_bytes=PIXEL_BYTES, subresource_alignment=16,
                order='mip_then_array_slice', mip_offset_rva=0x193bae0,
                mip_slice_size_rva=0x193ba50, upload_rva=0x19387d0,
                cpu_pointer_cleared_after_upload=True, streamed_part_count_offset=50,
                streamed_part_size_rva=0x139f7a0, streamed_part_address_rva=0x13b32f0,
                streamed_part_offset='totalSize - (levelCountAndSize >> 4)',
                streamed_part_size='cumulative size minus previous cumulative size')


def write_header(path):
    text = ('// Generated by scripts/mw19/generate_schema.py from Replay native image tables.\n'
            '#pragma once\n#include <array>\n#include <cstdint>\n\n'
            'namespace tool::mw19::schema::image_layout {\n')
    for name, values in [('Dxgi', DXGI), ('PixelBytes', PIXEL_BYTES)]:
        text += f'    inline constexpr std::array<uint32_t, {len(values)}> {name}{{{{\n        '
        text += ', '.join(map(str, values)) + '\n    }};\n'
    text += '} // namespace tool::mw19::schema::image_layout\n'
    if not path.exists() or path.read_text() != text: path.write_text(text)
